name: "F5 Contributor License Agreement"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have hereby read the F5 CLA and agree to its terms') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.F5_CLA_TOKEN }}
        with:
          path-to-signatures: 'signatures/beta/signatures.json'
          path-to-document: 'https://github.com/f5/.github/blob/main/CLA/cla-markdown.md'
          branch: 'master'
          custom-pr-sign-comment: 'I have hereby read the F5 CLA and agree to its terms'
          custom-notsigned-prcomment: '🎉 Thank you for your contribution. It appears you have not yet signed the F5 Contributor License Agreement, which is required for your changes to be incorporated into an F5 project. Please kindly read the [F5 CLA](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md) and comment the following to agree:'
          custom-allsigned-prcomment: 'All required contributors have signed the F5 CLA for this PR  ✅'
          remote-organization-name: 'f5'
          remote-repository-name: 'f5-cla-data'
          allowlist: 4141done, dekobon, bot*